
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/examples/table-angular
	@mkdir  ../../sea-modules/examples/table-angular
	@mkdir  ../../sea-modules/examples/table-angular/1.0.0
	@cp     dist/*.* ../../sea-modules/examples/table-angular/1.0.0
	@echo
	@echo   " deploy to seajs-modules/examples/table-angular/1.0.0"
	@echo
